language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "gt7pbngk8hcEsGRmjqy5/dFusFMQ5pKSptO++TGFC1PcXlKmzJpSRNbntGqAiwYwVfPH4bqwjM3xvzhUovwdkWHvAESaf4vewbPoWsG+hB0PO8AKEer+Xkwl6KODSk2a0/rU/EDDSYSDFCCLyPaEcDJfC6oMj9P+dAZZfG2HqSHi1dJ+m/6E2WzA5t1AjCbmg8FYV3vSIXyqk6mZM4cvJEEwNl9+ze6ubdFu0oqvSLjvRmAjbf4Oc+4VvSetq0PvyL5s2U3m1Wx0dSQA6c8tlERqPDISwp46Si4DfH/BCVmz/D0iSz1sMhaJx1M8GyiU33l6Xf7QHiuaz6TCSB4/bojM/NdDMij4m22h3tvNq3woO3m6DYUD2pIU4Sm3oi7PDQhUXY6/CNdf8Q6heRiaSgTXGRz87NQkNhXs+jIDT5dajrjVkSjZa3ENKTaN7G+ehwaGYoCWSdnXVO9EN1TSr0y+n4K3rP/iCbo7Snlz0Uv09UzN1WEk9aSDipyqpkrTw2bitqu1L4VD05wNbV4zMUxX92XXN0xTcb7hgPV4WAZE2fNb2fkdX6jI7Afzt/CeXRsR2/yjwV4UuJ0sWvIly7foBbqllcbOPMenpvxZ2GhsodcSMO/7M+TJ4n6HJfN/5IiI3jelGvKvZvkWfqIioGeaSPgdRC7X9END4nfJQU8="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
